### PR TITLE
Implement new code M38 - Compute SHA1 of target file

### PR DESCRIPTION
**Pull request by shaywood**
As it says on the tin. Useful for automation of file uploads if a newer version of a print is available, for example.

It can be quite slow to compute hashes on large files, but this is not surprising.

### CODE REVIEW

**Comment by chrishamm** [comment]
Thanks, I'll merge it into my fork once a description for M38 has been added to http://reprap.org/wiki/G-code. Could you do that?

**Comment by shaywood** [comment]
This is going to sound silly - but I can't find the "create account" or "signup" links anywhere on www.reprap.org/wiki, and do not have an account... 

Edit: http://forums.reprap.org/read.php?1,641102
I made a forum account to send a PM to get a wiki account so I can edit the page.

**Comment by shaywood** [comment]
Edit completed: http://reprap.org/wiki/G-code#M38_Compute_SHA1_hash_of_target_file

**Comment by shaywood** [comment]
Some additional testing revealed a bug with non-existent files broke the firmware. Fixed it by returning true when the file is not found.

**Comment by chrishamm** [comment]
There are a couple of possible bugs in there. I'll push my changes to GitHub tomrrow.

**Comment by chrishamm** [comment]
Thanks, I've merged your code into my fork with some more changes.

**Pull request closed without merging**
